import { ArrowLeft, ExternalLink } from "lucide-react";
import { useEffect, useRef } from "react";
import { Button } from "@/components/ui/button";
import { Progress } from "@/components/ui/progress";
import type { ToolViewModel } from "./data.js";
import { ToolFeedback } from "./tool-feedback.js";

export function ToolDetail({ tool, taskReason, mobileOpen = false, onMobileBack }: { tool: ToolViewModel; taskReason?: string; mobileOpen?: boolean; onMobileBack?: () => void }) {
  const dimensions = Object.entries(tool.rating.dimension_scores);
  const headingRef = useRef<HTMLHeadingElement>(null);
  useEffect(() => { if (mobileOpen) headingRef.current?.focus(); }, [mobileOpen, tool.card.id]);
  return <article className="min-w-0 rounded-xl border border-border bg-card p-5 shadow-sm md:p-7">
    {onMobileBack ? <Button className="mb-4 md:hidden" onClick={onMobileBack} variant="ghost"><ArrowLeft />Back to tools</Button> : null}
    <header className="grid gap-5 border-b border-border pb-6 sm:grid-cols-[1fr_auto]"><div><span className="font-mono text-xs font-semibold tracking-[.12em] text-primary uppercase">Verified decision record · {tool.card.type}</span><h2 className="mt-2 text-3xl font-semibold tracking-tight outline-none" ref={headingRef} tabIndex={-1}>{tool.card.name}</h2><p className="mt-2 max-w-3xl text-base leading-7 text-muted-foreground">{tool.card.summary}</p></div><div className="grid size-24 place-items-center rounded-xl border border-primary/25 bg-primary/8 text-center"><strong className="block text-4xl leading-none text-primary">{tool.rating.overall_score}</strong><span className="text-sm text-muted-foreground">{tool.rating.risk_level} risk</span></div></header>
    <section className="mt-5 rounded-lg border border-primary/20 bg-primary/6 p-4"><strong className="text-base">{taskReason ? "Why Radar recommends this" : "Why this rating"}</strong><p className="mt-1 text-[15px] leading-6 text-muted-foreground">{taskReason ?? tool.rating.explanations[0]?.reason ?? "Evidence-backed rating for this reviewed tool record."}</p></section>
    <ToolFeedback toolId={tool.card.id} />
    <div className="mt-5 grid grid-cols-2 gap-px overflow-hidden rounded-lg border border-border bg-border lg:grid-cols-4"><Fact label="Decision" value={tool.rating.recommendation_level} /><Fact label="Evidence" value={tool.rating.evidence_quality} /><Fact label="Maintenance" value={String(tool.rating.dimension_scores.maintenance_health ?? "unknown")} /><Fact label="Integration" value={String(tool.rating.dimension_scores.integration_cost ?? "unknown")} /></div>
    <div className="mt-5 grid gap-3 lg:grid-cols-2"><div className="rounded-lg bg-emerald-50 p-4"><strong>Good for</strong><p className="mt-1 text-[15px] leading-6 text-muted-foreground">{tool.card.use_cases.join(" · ") || "No reviewed use cases."}</p></div><div className="rounded-lg bg-amber-50 p-4"><strong>Not for</strong><p className="mt-1 text-[15px] leading-6 text-muted-foreground">{tool.card.not_for.join(" · ") || "No reviewed exclusions."}</p></div></div>
    <div className="mt-7 grid gap-8 xl:grid-cols-[1.15fr_.85fr]"><section><h3 className="mb-4 text-lg font-semibold">Decision signals</h3>{dimensions.map(([name, score]) => <div className="mb-4 grid grid-cols-[150px_1fr_38px] items-center gap-3 text-sm" key={name}><span className="capitalize text-muted-foreground">{name.replaceAll("_", " ")}</span><Progress value={score} /><strong className="font-mono text-right">{score}</strong></div>)}</section><aside><h3 className="mb-4 text-lg font-semibold">Evidence & access</h3><div className="divide-y divide-border rounded-lg border border-border"> <Info label="Primary source" value={tool.card.source_urls[0] ?? "No source"} link /><Info label="Permissions" value={tool.card.permissions.map((item) => `${item.scope}:${item.access}`).join(", ") || "None declared"} /><Info label="Security note" value={tool.card.security.security_notes} /><Info label="Last verified" value={tool.card.updated_at} /></div></aside></div>
  </article>;
}
function Fact({ label, value }: { label: string; value: string }) { return <div className="bg-card p-4"><span className="block text-xs font-semibold tracking-wide text-muted-foreground uppercase">{label}</span><strong className="mt-1 block text-base capitalize">{value}</strong></div>; }
function Info({ label, value, link = false }: { label: string; value: string; link?: boolean }) { return <div className="grid gap-1 p-4"><strong className="text-sm">{label}</strong>{link ? <a className="flex items-center gap-1 break-all text-sm text-primary hover:underline" href={value} rel="noreferrer" target="_blank">{value}<ExternalLink className="size-3.5 shrink-0" /></a> : <span className="text-sm leading-6 text-muted-foreground">{value}</span>}</div>; }
